services:
  mongo:
    container_name: "${APP_NAME:-mindMovment}-mongo"
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME:-reah}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD:-12345678}"
      MONGO_INITDB_DATABASE: "${MONGO_DB:-mind-movment}"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: "${APP_NAME:-mindMovment}-backend"
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    env_file:
      - ./src/backend/.env.development
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./src/backend/src:/app/src
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongo

  frontend:
    container_name: "${APP_NAME:-mindMovment}-frontend"
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    env_file:
      - ./src/frontend/.env.development
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - mongo
    command: npm run start

volumes:
  mongo-data:
